image_size: 256
in_channels: 3
model_channels: 256
out_channels: 6 # 3 if not learn_sigma else 6
num_res_blocks: 2
attention_resolutions: [8, 16, 32]
dropout: 0.1
channel_mult: [1, 1, 2 ,2, 4, 4]
num_classes: null 
use_checkpoint: false
use_fp16: false # if true, need to change ddpm pipeline
num_heads: 4 
num_head_channels: 64
num_heads_upsample: 4
use_scale_shift_norm: true
resblock_updown: true
use_new_attention_order: false