# ckpt path: pretrained/guided_diffusion/256x256_diffusion.pt
model: 
  image_size: 256
  num_channels: 256
  num_res_blocks: 2
  channel_mult: null
  learn_sigma: True
  class_cond: True
  use_checkpoint: False
  attention_resolutions: 32,16,8
  num_heads: 4
  num_head_channels: 64
  num_heads_upsample: -1
  use_scale_shift_norm: True
  dropout: 0.0
  resblock_updown: True
  use_fp16: True
  use_new_attention_order: False

# diffusion:
#   diffusion_steps: 1000
#   noise_schedule: linear
#   timestep_respacing: 
#   use_kl: False
#   predict_xstart: False
#   rescale_timesteps: False
#   rescale_learned_sigmas: False

# ckpt path: pretrained/guided_diffusion/256x256_classifier.pt
classifier:
  image_size: 256
  classifier_use_fp16: False
  classifier_width: 128
  classifier_depth: 2
  classifier_attention_resolutions: 32,16,8
  classifier_use_scale_shift_norm: True
  classifier_resblock_updown: True
  classifier_pool: attention