
out_dir: ./save
logging_dir: logs

train:
  num_epochs: 500
  mixed_precision: fp16
  gradient_accumulation_steps: 1
  use_ema: true
  save_images_epochs: 2
  save_model_epochs: 2

model:
  in_channels: 3
  out_ch: 3
  ch: 128
  ch_mult: [1, 1, 2, 2, 4, 4]
  num_res_blocks: 2
  attn_resolutions: [16, ]
  dropout: 0.0
  resamp_with_conv: True

optim:
  lr: 0.00002
  weight_decay: 0.0
  eps: 0.00000001

  lr_scheduler: cosine
  lr_warmup_steps: 500

ema:
  ema_inv_gamma: 1.0
  ema_power: 0.75
  ema_max_decay: 0.9999

data:
  name: cifar10
  cache_dir: ./data
  batch_size: 64
  eval_bs: 16
