project: diffusion_uncond
name: default
exp_dir: saves
save_dir: checkpoints
save_freq: 5
seed: 42

wandb: false


train:
  num_epochs: 100
  mixed_precision: fp16
  gradient_accumulation_steps: 1
  use_ema: true
  save_images_epochs: 5
  save_model_epochs: 5

model:
  resolution: 32
  in_channels: 3
  out_ch: 3
  ch: 128
  ch_mult: [1, 2, 2, 2]
  num_res_blocks: 2
  attn_resolutions: [16]
  dropout: 0.1

optim:
  lr: 0.00002
  weight_decay: 0.0
  eps: 0.00000001

  lr_scheduler: cosine
  lr_warmup_steps: 500

ema:
  ema_inv_gamma: 1.0
  ema_power: 0.75
  ema_max_decay: 0.9999

data:
  name: cifar10
  cache_dir: /nas/datasets/huggingface
  train_batch_size: 128
  eval_batch_size: 64
